### ISSUE TITLE
Memory leeks on windows

### ISSUE THREAD

**Issue by mjafartp** [kechankrisna/webcontent_converter#11]
In windows, it creates lots of chromium processes and does not close after use and in the background, it shows 20+ chromium processes. 
<img width="318" alt="Screenshot 2022-06-18 at 4 42 29 PM" src="https://user-images.githubusercontent.com/5754379/174435174-c6d1b393-30e4-487b-a3a6-f5fc0743644f.png">

**Comment by sbrsubuvga** [comment]
i have same issue.
it causes to crash my APP

**Comment by kechankrisna** [comment]
Please take a look the example, it will guide you how to close the browser when your app exit.

**Comment by plokmij** [comment]
I am getting this issue too. Did you find any workaround?
