### ISSUE TITLE
crash  in iOS

### ISSUE THREAD

**Issue by JagadishaIncture** [kechankrisna/webcontent_converter#12]
flutter: \^[[32m[webcontent_converter] [INFO] /Users/jagadishan/Library/Developer/CoreSimulator/Devices/8EE3E687-EBDF-4585-8AC8-E12F43E8EBEE/data/Containers/Data/Application/8677B062-73FD-4004-8ACB-843CB23ABA65/Library/Application Support/ahavri_home__18766.pdf<…>
flutter: \^[[32m[webcontent_converter] [INFO] {top: 0.3645833333333333, bottom: 0.3645833333333333, left: 0.3645833333333333, right: 0.3645833333333333}<…>
flutter: \^[[32m[webcontent_converter] [INFO] {width: 8.27, height: 11.7}<…>
flutter: \^[[32m[webcontent_converter] [INFO] Mobile support<…>
webcontent_converter/SwiftWebcontentConverterPlugin.swift:95: Fatal error: Unexpectedly found nil while unwrapping an Optional value

**Comment by JagadishaIncture** [comment]
issue is still there..crashing

**Comment by kechankrisna** [comment]
try to remove ios directory and recreate your flutter project again with flutter 3

**Comment by kechankrisna** [comment]
> flutter create -i swift . 
> 
> using this command?

Sure, but remove the ios directory first
