### ISSUE TITLE
Run IOS error

### ISSUE THREAD

**Issue by nambui2000k** [kechankrisna/webcontent_converter#15]
<img width="814" alt="Screen Shot 2022-06-28 at 14 21 34" src="https://user-images.githubusercontent.com/49670327/176118258-44a076e4-b95a-480b-98a7-9f5021e9462c.png">
Can you help me fix it?

**Comment by kechankrisna** [comment]
Please try new version, I just updated and tested for ios, android and macos

**Comment by nambui2000k** [comment]
<img width="841" alt="Screen Shot 2022-06-28 at 15 31 48" src="https://user-images.githubusercontent.com/49670327/176132859-cfe9b080-2347-4fa2-99c9-0be31d2100ac.png">
Thanks. I tried it. But having same error. You can help me?

**Comment by kechankrisna** [comment]
try to remove ios directory and recreate your flutter project again with flutter 3
