### ISSUE TITLE
Issue on android 12

### ISSUE THREAD

**Issue by prashantsachan98** [kechankrisna/webcontent_converter#16]
working perfectly fine on android 10 but contentToPDF is giving issue on android 11 and 12

` Future<void> generateExampleDocument(dynamic htmlContent) async {
    setState(() {
      isLoading = true;
    });

    var dir = await getApplicationDocumentsDirectory();
    var savedPath = dir.path + "_report.pdf";
    generatedPdfFilePath = await WebcontentConverter.contentToPDF(
      content: htmlContent,
      savedPath: savedPath,
      format: PaperFormat.a4,
      margins: PdfMargins.px(top: 35, bottom: 35, right: 35, left: 35),
    );
    Share.shareFiles([generatedPdfFilePath]);
    setState(() {
      isLoading = false;
    });
  }`

**Comment by SasithaDil** [comment]
This is not working. I'm Using android 11. it gives PlatformException
