### ISSUE TITLE
Images in web url is not loading in PDF

### ISSUE THREAD

**Issue by JagadishaIncture** [kechankrisna/webcontent_converter#7]
converted pdf doesnt contain images

weburl="http:\/\/rallyappliances.com\/rally_tally\/invoice1.php?order_id=13731&Cust_id=1"

`void savePdf() async {

    Utils.showLoaderDialogwithTitle(context,"Downloading...");

    var dir = await getExternalStorageDirectory();
    var savedPath = dir.path + "/" + webname + ".pdf";

    print(savedPath);

    var result = await WebcontentConverter.webUriToPdf(
      uri: weburl,
      savedPath: savedPath,
      format: PaperFormat.a4,
      margins: PdfMargins.px(top: 35, bottom: 35, right: 35, left: 35),
    );

    Navigator.pop(context);

    if (result != null) {
      OpenFile.open(savedPath);
      //launchURL(savedPath);
    } else {
      Utils.displayToast(context, "Something Went Wrong");
    }

  }`

**Comment by JagadishaIncture** [comment]
![WhatsApp Image 2022-03-03 at 11 11 37 AM (1)](https://user-images.githubusercontent.com/55983819/156503570-1565ad70-4a4d-4360-a99e-44d1f803229c.jpeg)
![WhatsApp Image 2022-03-03 at 11 11 37 AM](https://user-images.githubusercontent.com/55983819/156503580-eea369a7-09c1-48fe-8301-ac774bf13fa3.jpeg)

**Comment by kechankrisna** [comment]
Please try new version, I just updated and tested for ios, android and macos

**Comment by JagadishaIncture** [comment]
Fixed . 

Thanks a Lot

**Comment by swarupbhc** [comment]
hi @kechankrisna the issue is now appearing again, can you please check?


![Screenshot_1683055606](https://user-images.githubusercontent.com/55395995/235767057-8fba7698-d19d-43bf-a1dc-4c723b3b07fd.png)
![Screenshot_1683055617](https://user-images.githubusercontent.com/55395995/235767065-20a5844b-d905-44b0-b40e-734f48a862f6.png)

**Comment by Yannmm** [comment]
same issue for me.
